version: '3.9'
services:
  node_prismadb: 
    image: mongodb
    container_name: nodeprismadb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DBUSER}
      - MONGO_INITDB_ROOT_PASSWORD=${DBPASSWORD}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: